# Generated by Django 3.0.8 on 2020-07-01 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idx', models.IntegerField()),
                ('d_from', models.IntegerField()),
                ('d_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pts_from', models.IntegerField()),
                ('pts_to', models.IntegerField(blank=True)),
                ('bt_modifier', models.IntegerField()),
                ('dmg_modifier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lvl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idx', models.IntegerField()),
                ('idy', models.IntegerField(blank=True)),
                ('category', models.CharField(max_length=20)),
                ('multiplier', models.FloatField(blank=True)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponAvailability',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponConcealability',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponReliability',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponSubtype',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('short', models.CharField(max_length=4)),
                ('stun_save_mod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('accuracy', models.IntegerField()),
                ('damage', models.IntegerField(blank=True)),
                ('ammo', models.CharField(blank=True, max_length=20)),
                ('shots', models.IntegerField(blank=True)),
                ('rof', models.IntegerField(blank=True)),
                ('weapon_range', models.CharField(blank=True, max_length=20)),
                ('cost', models.IntegerField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('w_availability_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tinfoilpunk.WeaponAvailability')),
                ('w_concealability_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tinfoilpunk.WeaponConcealability')),
                ('w_reliability_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tinfoilpunk.WeaponReliability')),
                ('w_subtype_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tinfoilpunk.WeaponSubtype')),
                ('w_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tinfoilpunk.WeaponType')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('info', models.TextField(blank=True)),
                ('stat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tinfoilpunk.Stat')),
            ],
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.IntegerField(blank=True)),
                ('alt_no', models.IntegerField(blank=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinfoilpunk.Role')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinfoilpunk.Skill')),
            ],
        ),
    ]
