# Generated by Django 3.0.8 on 2020-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0002_auto_20200702_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
