# Generated by Django 3.0.8 on 2020-07-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0003_auto_20200702_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='pts_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
