# Generated by Django 3.0.8 on 2020-07-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0004_auto_20200702_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerskill',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='careerskill',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='stat_id',
            new_name='stat',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='w_availability_id',
            new_name='w_availability',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='w_concealability_id',
            new_name='w_concealability',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='w_reliability_id',
            new_name='w_reliability',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='w_subtype_id',
            new_name='w_subtype',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='w_type_id',
            new_name='w_type',
        ),
    ]
