# Generated by Django 3.0.8 on 2020-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0006_auto_20200702_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='ammo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rof',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='shots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
