# Generated by Django 3.0.8 on 2020-07-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0009_auto_20200702_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorMaterial',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('lvl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArmorPart',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='weapon',
            name='w_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='w_type', to='tinfoilpunk.WeaponType'),
        ),
    ]
