# Generated by Django 3.0.8 on 2020-07-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0010_auto_20200702_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='w_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tinfoilpunk.WeaponType'),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_head', models.IntegerField()),
                ('sp_torso', models.IntegerField()),
                ('sp_larm', models.IntegerField()),
                ('sp_rarm', models.IntegerField()),
                ('sp_lleg', models.IntegerField()),
                ('sp_rleg', models.IntegerField()),
                ('ev', models.IntegerField()),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='tinfoilpunk.ArmorMaterial')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='tinfoilpunk.ArmorPart')),
            ],
        ),
    ]
