# Generated by Django 3.0.8 on 2020-07-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0011_auto_20200702_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinfoilpunk.Race')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinfoilpunk.Stat')),
            ],
        ),
    ]
