# Generated by Django 3.0.8 on 2020-07-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0012_race_racebonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racebonus',
            old_name='value',
            new_name='modifier',
        ),
    ]
