# Generated by Django 3.0.8 on 2020-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0013_auto_20200703_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tinfoilware',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('info', models.TextField()),
            ],
        ),
    ]
