# Generated by Django 3.0.8 on 2020-07-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0017_auto_20200708_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npctinfoilware',
            options={'verbose_name_plural': 'Npc Tinfoilware'},
        ),
    ]
