# Generated by Django 3.0.8 on 2020-07-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0018_auto_20200708_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpcArmor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinfoilpunk.Armor')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinfoilpunk.Npc')),
            ],
            options={
                'verbose_name_plural': 'Npc Armor',
                'unique_together': {('npc', 'armor')},
            },
        ),
    ]
