# Generated by Django 3.0.8 on 2020-07-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0019_npcarmor'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='possessions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
