# Generated by Django 3.0.8 on 2020-07-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0021_auto_20200710_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racebonus',
            options={'ordering': ('race_id', 'stat_id'), 'verbose_name_plural': 'Race Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ('idx', 'idy')},
        ),
    ]
