# Generated by Django 3.0.8 on 2020-07-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0022_auto_20200710_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racebonus',
            options={'ordering': ('race_id', 'stat'), 'verbose_name_plural': 'Race Bonuses'},
        ),
    ]
