# Generated by Django 3.0.8 on 2020-07-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0023_auto_20200710_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodypart',
            options={'ordering': ('idx',), 'verbose_name_plural': 'Body Parts'},
        ),
        migrations.AlterModelOptions(
            name='bodytype',
            options={'ordering': ('pts_from',), 'verbose_name_plural': 'Body Types'},
        ),
        migrations.AlterModelOptions(
            name='careerskill',
            options={'ordering': ('role', 'skill'), 'verbose_name_plural': 'Career Skills'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='racebonus',
            options={'ordering': ('race', 'stat'), 'verbose_name_plural': 'Race Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('stat', 'id')},
        ),
    ]
