# Generated by Django 3.0.8 on 2020-07-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0024_auto_20200710_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='npcarmor',
            options={'ordering': ('npc', 'armor'), 'verbose_name_plural': 'Npc Armor'},
        ),
        migrations.AlterModelOptions(
            name='npcskill',
            options={'ordering': ('npc', 'skill'), 'verbose_name_plural': 'Npc Skills'},
        ),
        migrations.AlterModelOptions(
            name='npcstat',
            options={'ordering': ('npc', 'stat'), 'verbose_name_plural': 'Npc Stats'},
        ),
        migrations.AlterModelOptions(
            name='npctinfoilware',
            options={'ordering': ('npc', 'tinfoilware'), 'verbose_name_plural': 'Npc Tinfoilware'},
        ),
        migrations.AlterModelOptions(
            name='npcweapon',
            options={'ordering': ('npc', 'weapon'), 'verbose_name_plural': 'Npc Weapons'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ('w_type', 'w_subtype', 'id')},
        ),
        migrations.AlterModelOptions(
            name='wound',
            options={'ordering': ('-stun_save_mod',)},
        ),
    ]
