# Generated by Django 3.0.8 on 2020-08-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0026_auto_20200710_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'ordering': ('part', 'lvl', 'id')},
        ),
        migrations.AlterModelOptions(
            name='armorpart',
            options={'ordering': ('category', 'id'), 'verbose_name_plural': 'Armor Parts'},
        ),
        migrations.RemoveField(
            model_name='armor',
            name='material',
        ),
        migrations.AddField(
            model_name='armor',
            name='lvl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armorpart',
            name='category',
            field=models.CharField(default='nic', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armor',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ArmorMaterial',
        ),
    ]
