# Generated by Django 3.0.8 on 2020-08-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinfoilpunk', '0027_auto_20200805_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorBonusSp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pts_from', models.IntegerField()),
                ('pts_to', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
